[2024-06-28T18:04:16.420+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:04:16.441+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:04:05.063874+00:00 [queued]>
[2024-06-28T18:04:16.449+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:04:05.063874+00:00 [queued]>
[2024-06-28T18:04:16.449+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T18:04:16.460+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 18:04:05.063874+00:00
[2024-06-28T18:04:16.467+0000] {standard_task_runner.py:63} INFO - Started process 203 to run task
[2024-06-28T18:04:16.470+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T18:04:05.063874+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpszrz05ky']
[2024-06-28T18:04:16.472+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask data_delivery
[2024-06-28T18:04:16.513+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:04:05.063874+00:00 [running]> on host 79a59ce16f65
[2024-06-28T18:04:16.763+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T18:04:05.063874+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T18:04:05.063874+00:00'
[2024-06-28T18:04:16.764+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:04:16.777+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T18:04:16.777+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T18:04:16.785+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:04:16.788+0000] {Load_Data.py:89} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T18:04:16.790+0000] {Load_Data.py:143} INFO - Error loading location dimension: 'LocationID'
[2024-06-28T18:04:16.790+0000] {Load_Data.py:147} INFO - loading DimRate Dimension ...
[2024-06-28T18:04:16.793+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T18:04:16.795+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:04:16.802+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T18:04:16.802+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T18:04:16.803+0000] {Load_Data.py:150} INFO - DimRate_df dimension loaded successfully
[2024-06-28T18:04:16.803+0000] {Load_Data.py:165} INFO - loading payment dimension....
[2024-06-28T18:04:16.804+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T18:04:16.807+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:04:16.812+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T18:04:16.812+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T18:04:16.812+0000] {Load_Data.py:168} INFO - payment_df dimension loaded successfully
[2024-06-28T18:04:16.813+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T18:04:16.817+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:04:16.820+0000] {Load_Data.py:69} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T18:04:16.820+0000] {Load_Data.py:156} INFO - loading trip_type dimension....
[2024-06-28T18:04:16.822+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T18:04:16.825+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:04:16.829+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T18:04:16.829+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T18:04:16.829+0000] {Load_Data.py:159} INFO - trip_df dimension loaded successfully
[2024-06-28T18:04:16.829+0000] {Load_Data.py:174} INFO - loading fact table ....
[2024-06-28T18:04:20.375+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T18:04:20.378+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:07:30.099+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T18:07:30.099+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T18:07:35.622+0000] {Load_Data.py:196} INFO - Fact_df  loaded successfully
[2024-06-28T18:07:35.652+0000] {NYC_Taxi_pipeline.py:61} INFO - data_delivery done
[2024-06-28T18:07:35.652+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:07:35.653+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:07:35.662+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-28T18:04:05.063874+00:00, execution_date=20240628T180405, start_date=20240628T180416, end_date=20240628T180735
[2024-06-28T18:07:35.722+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:07:35.739+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:07:35.741+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
