[2024-06-28T19:15:56.801+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T19:15:56.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T19:15:46.142996+00:00 [queued]>
[2024-06-28T19:15:56.829+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T19:15:46.142996+00:00 [queued]>
[2024-06-28T19:15:56.830+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T19:15:56.841+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 19:15:46.142996+00:00
[2024-06-28T19:15:56.848+0000] {standard_task_runner.py:63} INFO - Started process 311 to run task
[2024-06-28T19:15:56.851+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T19:15:46.142996+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpvt5fssn2']
[2024-06-28T19:15:56.853+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask data_delivery
[2024-06-28T19:15:56.892+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T19:15:46.142996+00:00 [running]> on host 79a59ce16f65
[2024-06-28T19:15:57.140+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T19:15:46.142996+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T19:15:46.142996+00:00'
[2024-06-28T19:15:57.140+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T19:15:57.150+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T19:15:57.151+0000] {Load_Data.py:20} INFO - Loading location Dimension ...
[2024-06-28T19:15:57.157+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T19:15:57.295+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T19:15:57.297+0000] {Table_creation.py:30} INFO - Loading data into table DimLocation...
[2024-06-28T19:15:57.300+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T19:15:57.360+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimLocation With 265 Row
[2024-06-28T19:15:57.360+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T19:15:57.360+0000] {Load_Data.py:83} INFO - DimLocation dimension loaded successfully
[2024-06-28T19:15:57.361+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T19:15:57.361+0000] {Load_Data.py:91} INFO - loading DimRate Dimension ...
[2024-06-28T19:15:57.362+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T19:15:57.365+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T19:15:57.370+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T19:15:57.371+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T19:15:57.371+0000] {Load_Data.py:94} INFO - DimRate_df dimension loaded successfully
[2024-06-28T19:15:57.371+0000] {Load_Data.py:109} INFO - loading payment dimension....
[2024-06-28T19:15:57.373+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T19:15:57.376+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T19:15:57.382+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T19:15:57.382+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T19:15:57.383+0000] {Load_Data.py:112} INFO - payment_df dimension loaded successfully
[2024-06-28T19:15:57.383+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T19:15:57.385+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T19:15:57.388+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T19:15:57.392+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T19:15:57.393+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T19:15:57.393+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T19:15:57.393+0000] {Load_Data.py:100} INFO - loading trip_type dimension....
[2024-06-28T19:15:57.395+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T19:15:57.398+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T19:15:57.404+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T19:15:57.404+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T19:15:57.405+0000] {Load_Data.py:103} INFO - trip_df dimension loaded successfully
[2024-06-28T19:15:57.405+0000] {Load_Data.py:118} INFO - loading fact table ....
[2024-06-28T19:16:00.895+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T19:16:00.898+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T19:18:53.376+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T19:18:53.377+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T19:18:58.666+0000] {Load_Data.py:140} INFO - Fact_df  loaded successfully
[2024-06-28T19:18:58.694+0000] {NYC_Taxi_pipeline.py:61} INFO - data_delivery done
[2024-06-28T19:18:58.694+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T19:18:58.694+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T19:18:58.703+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-28T19:15:46.142996+00:00, execution_date=20240628T191546, start_date=20240628T191556, end_date=20240628T191858
[2024-06-28T19:18:58.735+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T19:18:58.750+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T19:18:58.751+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
