[2024-06-28T18:08:33.255+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:08:33.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:08:21.492751+00:00 [queued]>
[2024-06-28T18:08:33.284+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:08:21.492751+00:00 [queued]>
[2024-06-28T18:08:33.285+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T18:08:33.296+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 18:08:21.492751+00:00
[2024-06-28T18:08:33.303+0000] {standard_task_runner.py:63} INFO - Started process 212 to run task
[2024-06-28T18:08:33.306+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T18:08:21.492751+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpjxl8b3f0']
[2024-06-28T18:08:33.309+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask data_delivery
[2024-06-28T18:08:33.350+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:08:21.492751+00:00 [running]> on host 79a59ce16f65
[2024-06-28T18:08:33.634+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T18:08:21.492751+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T18:08:21.492751+00:00'
[2024-06-28T18:08:33.634+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:08:33.645+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T18:08:33.645+0000] {Load_Data.py:74} INFO - Loading location Dimension ...
[2024-06-28T18:08:33.651+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:08:33.654+0000] {Load_Data.py:90} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T18:08:33.656+0000] {Load_Data.py:144} INFO - Error loading location dimension: 'LocationID'
[2024-06-28T18:08:33.656+0000] {Load_Data.py:148} INFO - loading DimRate Dimension ...
[2024-06-28T18:08:33.658+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T18:08:33.661+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:08:33.667+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T18:08:33.667+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T18:08:33.667+0000] {Load_Data.py:151} INFO - DimRate_df dimension loaded successfully
[2024-06-28T18:08:33.667+0000] {Load_Data.py:166} INFO - loading payment dimension....
[2024-06-28T18:08:33.669+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T18:08:33.672+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:08:33.678+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T18:08:33.678+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T18:08:33.679+0000] {Load_Data.py:169} INFO - payment_df dimension loaded successfully
[2024-06-28T18:08:33.679+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T18:08:33.683+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:08:33.686+0000] {Load_Data.py:70} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T18:08:33.686+0000] {Load_Data.py:157} INFO - loading trip_type dimension....
[2024-06-28T18:08:33.687+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T18:08:33.690+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:08:33.695+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T18:08:33.695+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T18:08:33.695+0000] {Load_Data.py:160} INFO - trip_df dimension loaded successfully
[2024-06-28T18:08:33.696+0000] {Load_Data.py:175} INFO - loading fact table ....
[2024-06-28T18:08:37.693+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T18:08:37.696+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:11:36.465+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T18:11:36.466+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T18:11:41.687+0000] {Load_Data.py:197} INFO - Fact_df  loaded successfully
[2024-06-28T18:11:41.719+0000] {NYC_Taxi_pipeline.py:61} INFO - data_delivery done
[2024-06-28T18:11:41.719+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:11:41.720+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:11:41.728+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-28T18:08:21.492751+00:00, execution_date=20240628T180821, start_date=20240628T180833, end_date=20240628T181141
[2024-06-28T18:11:41.762+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:11:41.780+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:11:41.782+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
