[2024-06-28T17:50:16.121+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T17:50:16.142+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:50:04.833310+00:00 [queued]>
[2024-06-28T17:50:16.151+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:50:04.833310+00:00 [queued]>
[2024-06-28T17:50:16.151+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T17:50:16.162+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 17:50:04.833310+00:00
[2024-06-28T17:50:16.170+0000] {standard_task_runner.py:63} INFO - Started process 158 to run task
[2024-06-28T17:50:16.173+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T17:50:04.833310+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmptmdzh66g']
[2024-06-28T17:50:16.175+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask data_delivery
[2024-06-28T17:50:16.216+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:50:04.833310+00:00 [running]> on host 79a59ce16f65
[2024-06-28T17:50:16.451+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T17:50:04.833310+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T17:50:04.833310+00:00'
[2024-06-28T17:50:16.452+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T17:50:16.461+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T17:50:16.462+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T17:50:16.468+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:50:16.472+0000] {Load_Data.py:90} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T17:50:16.472+0000] {Load_Data.py:145} INFO - Error loading location dimension: 'LocationID'
[2024-06-28T17:50:16.472+0000] {Load_Data.py:149} INFO - loading DimRate Dimension ...
[2024-06-28T17:50:16.474+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T17:50:16.477+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:50:16.482+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T17:50:16.483+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:50:16.483+0000] {Load_Data.py:152} INFO - DimRate_df dimension loaded successfully
[2024-06-28T17:50:16.483+0000] {Load_Data.py:167} INFO - loading payment dimension....
[2024-06-28T17:50:16.485+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T17:50:16.488+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:50:16.493+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T17:50:16.493+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:50:16.493+0000] {Load_Data.py:170} INFO - payment_df dimension loaded successfully
[2024-06-28T17:50:16.493+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T17:50:16.498+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:50:16.502+0000] {Load_Data.py:69} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T17:50:16.502+0000] {Load_Data.py:158} INFO - loading trip_type dimension....
[2024-06-28T17:50:16.504+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T17:50:16.507+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:50:16.512+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T17:50:16.512+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:50:16.512+0000] {Load_Data.py:161} INFO - trip_df dimension loaded successfully
[2024-06-28T17:50:16.512+0000] {Load_Data.py:176} INFO - loading fact table ....
[2024-06-28T17:50:19.768+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T17:50:19.772+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:53:29.474+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T17:53:29.475+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:53:35.324+0000] {Load_Data.py:198} INFO - Fact_df  loaded successfully
[2024-06-28T17:53:35.353+0000] {NYC_Taxi_pipeline.py:61} INFO - data_delivery done
[2024-06-28T17:53:35.354+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T17:53:35.354+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T17:53:35.365+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-28T17:50:04.833310+00:00, execution_date=20240628T175004, start_date=20240628T175016, end_date=20240628T175335
[2024-06-28T17:53:35.401+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T17:53:35.416+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T17:53:35.417+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
