[2024-06-28T17:13:44.949+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T17:13:44.969+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:13:34.997134+00:00 [queued]>
[2024-06-28T17:13:44.977+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:13:34.997134+00:00 [queued]>
[2024-06-28T17:13:44.977+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T17:13:44.988+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 17:13:34.997134+00:00
[2024-06-28T17:13:44.996+0000] {standard_task_runner.py:63} INFO - Started process 86 to run task
[2024-06-28T17:13:44.999+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T17:13:34.997134+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp00chmsa7']
[2024-06-28T17:13:45.001+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask data_delivery
[2024-06-28T17:13:45.041+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:13:34.997134+00:00 [running]> on host 79a59ce16f65
[2024-06-28T17:13:45.317+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T17:13:34.997134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T17:13:34.997134+00:00'
[2024-06-28T17:13:45.318+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T17:13:45.330+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T17:13:45.330+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T17:13:45.334+0000] {Load_Data.py:75} INFO - CSV columns: ['LocationID', 'Borough', 'Zone', 'service_zone']
[2024-06-28T17:13:45.341+0000] {Load_Data.py:76} INFO - CSV data sample:
   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone
[2024-06-28T17:13:45.344+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:13:45.348+0000] {Load_Data.py:90} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T17:13:45.348+0000] {Load_Data.py:145} INFO - Error loading location dimension: 'LocationID'
[2024-06-28T17:13:45.349+0000] {Load_Data.py:149} INFO - loading DimRate Dimension ...
[2024-06-28T17:13:45.351+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T17:13:45.354+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:13:45.359+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T17:13:45.359+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:13:45.359+0000] {Load_Data.py:152} INFO - DimRate_df dimension loaded successfully
[2024-06-28T17:13:45.359+0000] {Load_Data.py:167} INFO - loading payment dimension....
[2024-06-28T17:13:45.361+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T17:13:45.364+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:13:45.370+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T17:13:45.370+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:13:45.371+0000] {Load_Data.py:170} INFO - payment_df dimension loaded successfully
[2024-06-28T17:13:45.371+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T17:13:45.375+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:13:45.378+0000] {Load_Data.py:69} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T17:13:45.378+0000] {Load_Data.py:158} INFO - loading trip_type dimension....
[2024-06-28T17:13:45.380+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T17:13:45.383+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:13:45.389+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T17:13:45.389+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:13:45.389+0000] {Load_Data.py:161} INFO - trip_df dimension loaded successfully
[2024-06-28T17:13:45.389+0000] {Load_Data.py:176} INFO - loading fact table ....
[2024-06-28T17:13:48.653+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T17:13:48.656+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:16:38.487+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T17:16:38.488+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:16:43.894+0000] {Load_Data.py:198} INFO - Fact_df  loaded successfully
[2024-06-28T17:16:43.919+0000] {NYC_Taxi_pipeline.py:61} INFO - data_delivery done
[2024-06-28T17:16:43.920+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T17:16:43.920+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T17:16:43.928+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-28T17:13:34.997134+00:00, execution_date=20240628T171334, start_date=20240628T171344, end_date=20240628T171643
[2024-06-28T17:16:43.971+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T17:16:43.987+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T17:16:43.988+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
