[2024-06-28T18:51:05.386+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:51:05.407+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:50:55.420131+00:00 [queued]>
[2024-06-28T18:51:05.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:50:55.420131+00:00 [queued]>
[2024-06-28T18:51:05.414+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T18:51:05.425+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 18:50:55.420131+00:00
[2024-06-28T18:51:05.432+0000] {standard_task_runner.py:63} INFO - Started process 266 to run task
[2024-06-28T18:51:05.434+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T18:50:55.420131+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp_w7ws28y']
[2024-06-28T18:51:05.437+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask data_delivery
[2024-06-28T18:51:05.486+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T18:50:55.420131+00:00 [running]> on host 79a59ce16f65
[2024-06-28T18:51:05.763+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T18:50:55.420131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T18:50:55.420131+00:00'
[2024-06-28T18:51:05.764+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:51:05.774+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T18:51:05.775+0000] {Load_Data.py:20} INFO - Loading location Dimension ...
[2024-06-28T18:51:05.781+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:51:05.785+0000] {Load_Data.py:38} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T18:51:05.917+0000] {Table_creation.py:30} INFO - Loading data into table DimLocation...
[2024-06-28T18:51:05.920+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T18:54:37.540+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T18:54:37.542+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:54:37.544+0000] {process_utils.py:132} INFO - Sending 15 to group 266. PIDs of all processes in the group: [266]
[2024-06-28T18:54:37.545+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 266
[2024-06-28T18:55:37.548+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=266, name='airflow task ru', status='sleeping', started='18:51:04') did not respond to SIGTERM. Trying SIGKILL
[2024-06-28T18:55:37.549+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 266
[2024-06-28T18:55:37.563+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=266, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='18:51:04') (266) terminated with exit code -9
[2024-06-28T18:55:37.563+0000] {standard_task_runner.py:178} ERROR - Job 98 was killed before it finished (likely due to running out of memory)
