[2024-06-28T17:35:56.635+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T17:35:56.656+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:35:46.185886+00:00 [queued]>
[2024-06-28T17:35:56.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:35:46.185886+00:00 [queued]>
[2024-06-28T17:35:56.664+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T17:35:56.675+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 17:35:46.185886+00:00
[2024-06-28T17:35:56.682+0000] {standard_task_runner.py:63} INFO - Started process 131 to run task
[2024-06-28T17:35:56.686+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T17:35:46.185886+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp19nap_04']
[2024-06-28T17:35:56.689+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask data_delivery
[2024-06-28T17:35:56.749+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:35:46.185886+00:00 [running]> on host 79a59ce16f65
[2024-06-28T17:35:57.076+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T17:35:46.185886+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T17:35:46.185886+00:00'
[2024-06-28T17:35:57.077+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T17:35:57.087+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T17:35:57.087+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T17:35:57.094+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:35:57.241+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:38:48.402+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T17:38:48.403+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T17:38:48.404+0000] {process_utils.py:132} INFO - Sending 15 to group 131. PIDs of all processes in the group: [131]
[2024-06-28T17:38:48.404+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 131
[2024-06-28T17:39:48.405+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=131, name='airflow task ru', status='sleeping', started='17:35:56') did not respond to SIGTERM. Trying SIGKILL
[2024-06-28T17:39:48.406+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 131
[2024-06-28T17:39:48.420+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=131, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='17:35:56') (131) terminated with exit code -9
[2024-06-28T17:39:48.421+0000] {standard_task_runner.py:178} ERROR - Job 53 was killed before it finished (likely due to running out of memory)
