[2024-06-28T13:55:49.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T13:55:49.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T13:55:37.686258+00:00 [queued]>
[2024-06-28T13:55:49.922+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T13:55:37.686258+00:00 [queued]>
[2024-06-28T13:55:49.922+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T13:55:49.933+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 13:55:37.686258+00:00
[2024-06-28T13:55:49.940+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-06-28T13:55:49.942+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T13:55:37.686258+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpnt_0e61c']
[2024-06-28T13:55:49.945+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask data_delivery
[2024-06-28T13:55:49.984+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T13:55:37.686258+00:00 [running]> on host 79a59ce16f65
[2024-06-28T13:55:50.218+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T13:55:37.686258+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T13:55:37.686258+00:00'
[2024-06-28T13:55:50.219+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T13:55:50.230+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T13:55:50.230+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T13:55:50.236+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T13:55:50.240+0000] {Load_Data.py:141} INFO - Error loading location dimension: 'LocationID'
[2024-06-28T13:55:50.240+0000] {Load_Data.py:145} INFO - loading DimRate Dimension ...
[2024-06-28T13:55:50.242+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T13:55:50.246+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T13:55:50.252+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T13:55:50.252+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T13:55:50.253+0000] {Load_Data.py:148} INFO - DimRate_df dimension loaded successfully
[2024-06-28T13:55:50.253+0000] {Load_Data.py:163} INFO - loading payment dimension....
[2024-06-28T13:55:50.254+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T13:55:50.257+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T13:55:50.264+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T13:55:50.264+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T13:55:50.264+0000] {Load_Data.py:166} INFO - payment_df dimension loaded successfully
[2024-06-28T13:55:50.264+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T13:55:50.269+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T13:55:50.272+0000] {Load_Data.py:69} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T13:55:50.272+0000] {Load_Data.py:154} INFO - loading trip_type dimension....
[2024-06-28T13:55:50.274+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T13:55:50.277+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T13:55:50.282+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T13:55:50.283+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T13:55:50.283+0000] {Load_Data.py:157} INFO - trip_df dimension loaded successfully
[2024-06-28T13:55:50.283+0000] {Load_Data.py:172} INFO - loading fact table ....
[2024-06-28T13:55:53.749+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T13:55:53.753+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T13:59:12.679+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T13:59:12.680+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T13:59:18.077+0000] {Load_Data.py:194} INFO - Fact_df  loaded successfully
[2024-06-28T13:59:18.122+0000] {NYC_Taxi_pipeline.py:61} INFO - data_delivery done
[2024-06-28T13:59:18.123+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T13:59:18.123+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T13:59:18.132+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-28T13:55:37.686258+00:00, execution_date=20240628T135537, start_date=20240628T135549, end_date=20240628T135918
[2024-06-28T13:59:18.198+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T13:59:18.211+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T13:59:18.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
